CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_on DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS urls (
  id INTEGER PRIMARY KEY,
  long_url TEXT NOT NULL,
  short_url TEXT NOT NULL,
  created_on DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER,
  FOREIGN KEY(user_id) REFERENCES users(id),
  UNIQUE (user_id, long_url)
);

CREATE TABLE IF NOT EXISTS custom_urls (
  name TEXT NOT NULL,
  url_id INTEGER UNIQUE,
  FOREIGN KEY(url_id) REFERENCES urls(id)
);
